apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-servicebus-exporter
  labels:
    app: azure-servicebus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-servicebus-exporter
  template:
    metadata:
      labels:
        app: azure-servicebus-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: azure-servicebus-exporter
      containers:
        - name: exporter
          image: yourregistry/azure-servicebus-exporter:latest
          imagePullPolicy: Always
          args:
            - "--config"
            - "/etc/azure-servicebus-exporter/config.yaml"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/azure-servicebus-exporter
            - name: secrets
              mountPath: /etc/azure-servicebus-exporter/secrets
              readOnly: true
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config
          configMap:
            name: azure-servicebus-exporter
        - name: secrets
          secret:
            secretName: azure-servicebus-exporter