apiVersion: v1
kind: Secret
metadata:
  name: azure-servicebus-exporter
type: Opaque
data:
  # Base64-encoded connection string or Azure credentials
  connection_string: ""  # echo -n "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxx" | base64
  tenant_id: ""          # echo -n "tenant-id" | base64
  client_id: ""          # echo -n "client-id" | base64
  client_secret: ""      # echo -n "client-secret" | base64