apiVersion: v1
kind: Service
metadata:
  name: azure-servicebus-exporter
  labels:
    app: azure-servicebus-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: azure-servicebus-exporter