apiVersion: v2
name: azure-servicebus-exporter
description: A Helm chart for Prometheus exporter for Azure Service Bus
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com