# Default values for azure-servicebus-exporter
replicaCount: 1

image:
  repository: yourregistry/azure-servicebus-exporter
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  server:
    listen: ":8080"
    timeout: 30s
  
  auth:
    # Mode can be "connection_string" or "azure_auth"
    mode: "connection_string"
    
    # Connection string (used in connection_string mode)
    # Leave empty to use secret
    connectionString: ""
    
    # Azure auth (used in azure_auth mode)
    tenantId: ""
    clientId: ""
    clientSecret: ""
    useManagedIdentity: false
  
  azureMonitor:
    subscriptionIds: []
  
  metrics:
    namespace: "azure_servicebus"
    template: "{namespace}_{metric}_{aggregation}_{unit}"
    cacheDuration: "1m"
    scrapeInterval: "1m"
  
  servicebus:
    namespaces: []
    entityFilter: ".*"
    entityTypes:
      - "queue"
      - "topic"
      - "subscription"
    includeNamespace: true
  
  kubernetes:
    secretName: ""
    secretNamespace: ""
    secretKey: "connection_string"
  
  logging:
    level: "info"
    format: "json"

# Secret configuration
secret:
  create: true
  # Use existing secret instead (if create is false)
  existingSecret: ""
  # Secret data
  data:
    connection_string: ""
    tenant_id: ""
    client_id: ""
    client_secret: ""